# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-27 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_unit', models.CharField(max_length=50)),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('bedrooms', models.IntegerField()),
                ('home_size', models.IntegerField()),
                ('home_type', models.CharField(choices=[('Apartment', 'Apartment'), ('Duplex', 'Duplex'), ('VacantResidentialLand', 'Vacant Residential Land'), ('Miscellaneous', 'Miscellaneous'), ('SingleFamily', 'Single Family'), ('MultiFamily2To4', 'Multi Family (2 to 4 people)'), ('Condominium', 'Condominium')], max_length=50)),
                ('last_sold_date', models.DateTimeField(blank=True, null=True)),
                ('last_sold_price', models.IntegerField(blank=True, null=True)),
                ('link', models.TextField()),
                ('rent_price', models.IntegerField()),
                ('rentzestimate_amount', models.IntegerField()),
                ('tax_year', models.DateTimeField(blank=True, null=True)),
                ('year_built', models.DateTimeField(blank=True, null=True)),
                ('zestimate_amount', models.IntegerField()),
                ('zillow_id', models.BigIntegerField()),
                ('address', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('zipcode', models.TextField()),
            ],
        ),
    ]
